# Generated by Django 3.2.5 on 2023-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('IDART', models.AutoField(primary_key=True, serialize=False)),
                ('RefArt', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('TypeArt', models.CharField(max_length=255)),
                ('LOT', models.CharField(max_length=255)),
                ('Conditionnement', models.CharField(max_length=255)),
                ('CATEGORIE', models.CharField(max_length=255)),
                ('TauxTVA', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PUSansBIC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('REMISE', models.DecimalField(decimal_places=2, max_digits=5)),
                ('STOCKMIN', models.PositiveIntegerField()),
                ('QTEENTREE', models.PositiveIntegerField()),
                ('QTESORTIE', models.PositiveIntegerField()),
                ('PumACHAT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PumVENTE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QTESTOCK', models.PositiveIntegerField()),
                ('TOTALSTOCK', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ETATSTOCK', models.CharField(max_length=255)),
                ('DatePremption', models.DateField()),
                ('TEXT', models.TextField()),
            ],
        ),
    ]
