# Generated by Django 3.2.5 on 2023-09-27 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('designation', models.CharField(max_length=255, unique=True)),
                ('type_article', models.CharField(max_length=255)),
                ('lot', models.CharField(max_length=255)),
                ('packaging', models.CharField(max_length=255)),
                ('remise', models.IntegerField()),
                ('quantity_in', models.IntegerField()),
                ('quantity_out', models.IntegerField()),
                ('one_sell_price', models.IntegerField()),
                ('total_stock', models.IntegerField()),
                ('state_stock', models.SmallIntegerField()),
                ('DatePremption', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='articleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BC_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_one', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.article')),
            ],
        ),
        migrations.CreateModel(
            name='BL_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_one', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.article')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ifu', models.CharField(max_length=255, unique=True)),
                ('rccm', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('num_proforma', models.AutoField(primary_key=True, serialize=False)),
                ('date_proforma', models.DateTimeField()),
                ('total_ht', models.IntegerField()),
                ('total_bic', models.IntegerField()),
                ('frais_livraison', models.IntegerField()),
                ('total_tva', models.IntegerField()),
                ('total_ttc', models.IntegerField()),
                ('remise', models.IntegerField()),
                ('net_a_payer', models.IntegerField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.client')),
            ],
        ),
        migrations.CreateModel(
            name='Pro_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.article')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.proforma')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=255, unique=True)),
                ('fax', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ifu', models.CharField(max_length=255, unique=True)),
                ('rccm', models.CharField(max_length=255, unique=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_facture', models.IntegerField(unique=True)),
                ('create_at', models.DateTimeField()),
                ('nature_facture', models.CharField(max_length=255)),
                ('total_ht', models.IntegerField()),
                ('total_bic', models.IntegerField()),
                ('frais_transport', models.IntegerField()),
                ('remise', models.IntegerField()),
                ('total_remise', models.IntegerField()),
                ('total_ttc', models.IntegerField()),
                ('net_a_payer', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.clientcategory'),
        ),
        migrations.AddField(
            model_name='client',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ville'),
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('mode_bl', models.CharField(max_length=255)),
                ('total_ht', models.IntegerField()),
                ('frais_transport', models.IntegerField()),
                ('blarticles', models.ManyToManyField(to='stock.BL_article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.client')),
            ],
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('ref_piece', models.CharField(max_length=255)),
                ('frais_transport', models.IntegerField()),
                ('total_bic', models.IntegerField()),
                ('total_ht', models.IntegerField()),
                ('total_tva', models.IntegerField()),
                ('remise', models.IntegerField()),
                ('total_ttc', models.IntegerField()),
                ('total_remise', models.IntegerField()),
                ('net_a_payer', models.IntegerField()),
                ('bcarticles', models.ManyToManyField(to='stock.BC_article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='BL_Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.bonlivraison')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.facture')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.articlecategory'),
        ),
    ]
